#!/bin/bash
#
#SBATCH --job-name=Dwarf_Gal_Bursts
#SBATCH --output=dwarf_gal_heimdall
#
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --gres=gpu:1
#SBATCH --time=12:00:00
#SBATCH --mem-per-cpu=8g

source /home/hqiu/psrhome_2019-03.sh

while read line;do  mkdir $line.cands;
heimdall -f $line -dm 0 4000 -boxcar_max 2048 -output_dir $line.cands;
cat $line.cands/*.cand > $line.hmd.cand;  done < fillist
